# QA Environment
base.url=https://www.saucedemo.com
standard.user=standard_user
locked.user=locked_out_user
problem.user=problem_user
password=secret_sauce
implicit.wait=10
explicit.wait=15
page.load.timeout=30
